version: "3"
services:
  demo:
    build: ./demo
    command: "streamlit run ui.py"
    ports:
      - "8501:8501"
    depends_on:
      - redisai
  redisai:
    image: redislabs/redisai:edge-cpu
    volumes:
      - ./redisai:/data
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - |
          redis-server --loadmodule /usr/lib/redis/modules/redisai.so &
          sleep 5
          cat /data/exported/resnet50.pb | redis-cli -x AI.MODELSTORE imagenet_model TF CPU TAG imagenet:5.0 INPUTS 1 images OUTPUTS 1 output BLOB
          cat /data/data_processing_script.txt | redis-cli -x AI.SCRIPTSET imagenet_script CPU TAG imagenet_script:v0.1 SOURCE
          tail -f /dev/null
